apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          env:
            - name: DATABASE_URL
              value: "postgresql://{{ .Values.db.user }}:{{ .Values.db.password }}@db:5432/{{ .Values.db.name }}"
          ports:
            - containerPort: 8000